//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     To add or modify a string, edit Strings.resx and save; the designer file
//     will be regenerated automatically by Visual Studio.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CornealiusEyeworth.Localization {
    using System;
    using System.Reflection;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {

        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;

        internal Strings() {}

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CornealiusEyeworth.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        internal static string AppName => ResourceManager.GetString("AppName", resourceCulture)!;
        internal static string AppTitle => ResourceManager.GetString("AppTitle", resourceCulture)!;
        internal static string GitHubUrl => ResourceManager.GetString("GitHubUrl", resourceCulture)!;
        internal static string StatusServing => ResourceManager.GetString("StatusServing", resourceCulture)!;
        internal static string ScheduleDescription => ResourceManager.GetString("ScheduleDescription", resourceCulture)!;
        internal static string NextTrigger => ResourceManager.GetString("NextTrigger", resourceCulture)!;
        internal static string LanguageDialogTitle => ResourceManager.GetString("LanguageDialogTitle", resourceCulture)!;
        internal static string MenuLanguage => ResourceManager.GetString("MenuLanguage", resourceCulture)!;
        internal static string MenuOptions => ResourceManager.GetString("MenuOptions", resourceCulture)!;
        internal static string MenuTriggerTimes => ResourceManager.GetString("MenuTriggerTimes", resourceCulture)!;
        internal static string MenuHelp => ResourceManager.GetString("MenuHelp", resourceCulture)!;
        internal static string MenuAbout => ResourceManager.GetString("MenuAbout", resourceCulture)!;
        internal static string MenuGitHub => ResourceManager.GetString("MenuGitHub", resourceCulture)!;
        internal static string ScheduleDialogTitle => ResourceManager.GetString("ScheduleDialogTitle", resourceCulture)!;
        internal static string OptionsInstruction => ResourceManager.GetString("OptionsInstruction", resourceCulture)!;
        internal static string ButtonSave => ResourceManager.GetString("ButtonSave", resourceCulture)!;
        internal static string ButtonCancel => ResourceManager.GetString("ButtonCancel", resourceCulture)!;
        internal static string AboutDialogTitle => ResourceManager.GetString("AboutDialogTitle", resourceCulture)!;
        internal static string AboutDescription => ResourceManager.GetString("AboutDescription", resourceCulture)!;
        internal static string AboutVersion => ResourceManager.GetString("AboutVersion", resourceCulture)!;
        internal static string ButtonClose => ResourceManager.GetString("ButtonClose", resourceCulture)!;
        internal static string NotificationOnDuty => ResourceManager.GetString("NotificationOnDuty", resourceCulture)!;
        internal static string ParseErrorNoMinutes => ResourceManager.GetString("ParseErrorNoMinutes", resourceCulture)!;
        internal static string ParseErrorInvalidMinute => ResourceManager.GetString("ParseErrorInvalidMinute", resourceCulture)!;
        internal static string OptionsLanguageLabel => ResourceManager.GetString("OptionsLanguageLabel", resourceCulture)!;
        internal static string OptionsLanguageDefault => ResourceManager.GetString("OptionsLanguageDefault", resourceCulture)!;
        internal static string OptionsLanguageRestartNotice => ResourceManager.GetString("OptionsLanguageRestartNotice", resourceCulture)!;
        internal static string ScheduleDescriptionCron => ResourceManager.GetString("ScheduleDescriptionCron", resourceCulture)!;
        internal static string ScheduleDescriptionSimple => ResourceManager.GetString("ScheduleDescriptionSimple", resourceCulture)!;
        internal static string ScheduleSimpleRadio => ResourceManager.GetString("ScheduleSimpleRadio", resourceCulture)!;
        internal static string ScheduleAdvancedRadio => ResourceManager.GetString("ScheduleAdvancedRadio", resourceCulture)!;
        internal static string ScheduleCronInstruction => ResourceManager.GetString("ScheduleCronInstruction", resourceCulture)!;
        internal static string ParseErrorCronEmpty => ResourceManager.GetString("ParseErrorCronEmpty", resourceCulture)!;
        internal static string ParseErrorCronInvalid => ResourceManager.GetString("ParseErrorCronInvalid", resourceCulture)!;
        internal static string FatalErrorTitle => ResourceManager.GetString("FatalErrorTitle", resourceCulture)!;
        internal static string FatalErrorMessage => ResourceManager.GetString("FatalErrorMessage", resourceCulture)!;
    }
}
